
/////////PETICIONES BÁSICAS/////////

GET http://localhost:3000/api/users

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
"name": "Marta",
"surname": "Vázquez",
"username": "martav69",
"email": "martav69@gmail.com",
"password": "12345",
"phone": "666999222",
"hobbies": "cine, novela negra, fotografía",
"personality": "Conozco al detalle cada película de Wong Kar Wai",
"birth_date": "1983-05-09",
"rating": 2
}

###
PUT http://localhost:3000/api/users/4
Content-Type: application/json

{
"name": "Maite",
"surname": "Ramirez",
"username": "miren88",
"email": "mramirez@gmail.com",
"password": "12345",
"phone": "666777888",
"hobbies": "escalada, gastronomia, manualidades",
"personality": "Me encanta viajar y conocer gente nueva",
"birth_date": "1988-05-12",
"rating": "3"
}

###
DELETE http://localhost:3000/api/users/1
###


/////////PETICIONES AVANZADAS/////////

//GET USER BY ID
GET http://localhost:3000/api/users/4
###

//GET USERS BY TRIP
GET http://localhost:3000/api/trips/5
###

//REGISTER (password encriptación)
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
"name": "Leire",
"surname": "Seoane",
"username": "leiseo",
"email": "leiseo@gmail.com",
"password": "12345",
"phone": "666555000",
"hobbies": "cocinar, historia, arte medieval",
"personality": "Sin ser yo gótica, me encanta el gótico",
"birth_date": "1988-02-23",
"rating": 5
}
###

//LOGIN (token auth)
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "leire87@gmail.com",
    "password": "123456"
}
###

//GET USERS BY TRIP
GET http://localhost:3000/api/users/trip/5


###
// EDITAR MY PROFILE
PUT http://localhost:3000/api/users/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxOCwiZXhwX2F0IjoxNjcyOTA2NjY5LCJpYXQiOjE2NzExNzg2Njl9.-TCWNVtCoDaVCw8UASP3xW-QtQT5qscKeck8ldvJPxA

{
    "name": "Leiiiiire", 
    "surname": "G", 
    "username": "leire2",
    "email": "leire87@gmail.com",  
    "phone": "66777777", 
    "hobbies": "me gusta la pesca y el tiro con arco", 
    "personality": "tengo personalidad",
    "birth_date": "1990/03/02",
    "img_users": ""
}

###

// Recupera el perfil del usuario logado
GET http://localhost:3000/api/users/profile
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxOCwiZXhwX2F0IjoxNjcyODQ5MjYzLCJpYXQiOjE2NzExMjEyNjN9.uSNVibyROpFxMWeyxmV9Iex0RELBRF2fnCYcGlqIYpc


