
/////////PETICIONES BÁSICAS/////////

GET http://localhost:3000/api/trips

###
POST http://localhost:3000/api/trips
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxOCwiZXhwX2F0IjoxNjcyODMyNzI3LCJpYXQiOjE2NzExMDQ3Mjd9.x8Y27M0nsFthq4aqz3P2AhSIaL-GInTSTIYYQ0kABk0

{
"destination": "Chicago",
"min_traveler": 3,
"max_traveler": 5,
"min_age": 25,
"max_age":53,
"departure_date": "2022-11-11",
"duration": 6,
"price": 544,
"description": "Visita a la ciudad de Chicago y su arquitectura",
"status": "finalizado",
"flights": true, "hotel": true, "meals": false, "excursions": true, "rent_car": false, "insurance": false
}

###
PUT http://localhost:3000/api/trips/1
Content-Type: application/json

{
"destination": "Chicago",
"min_traveler": 4,
"max_traveler": 6,
"min_age": 25,
"max_age":53,
"departure_date": "2022-11-11",
"duration": 6,
"price": 544,
"description": "viaje a chicago"
}

###
DELETE http://localhost:3000/api/trips/8
###


/////////PETICIONES AVANZADAS/////////

//GET TRIP BY ID
GET http://localhost:3000/api/trips/25
###

//GET TRIPS BY DESTINATION
GET http://localhost:3000/api/trips/destination/creta
###

//GET ALL DESTINATIONS
GET http://localhost:3000/api/trips/destination
###

//GET TRIPS BY USER
GET http://localhost:3000/api/trips/user/6
###

//GET TRIPS CREATED BY USER LOGGED
GET http://localhost:3000/api/trips/user/created
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxOCwiZXhwX2F0IjoxNjcyODMyNzI3LCJpYXQiOjE2NzExMDQ3Mjd9.x8Y27M0nsFthq4aqz3P2AhSIaL-GInTSTIYYQ0kABk0
###

//GET TRIPS SUSCRIBED BY USER LOGGED
GET http://localhost:3000/api/trips/user/suscribed
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxOCwiZXhwX2F0IjoxNjcyODMyNzI3LCJpYXQiOjE2NzExMDQ3Mjd9.x8Y27M0nsFthq4aqz3P2AhSIaL-GInTSTIYYQ0kABk0
###

//POST COMMENT
POST http://localhost:3000/api/trips/comment/new
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMiwiZXhwX2F0IjoxNjcyNjU4ODE1LCJpYXQiOjE2NzA5MzA4MTV9.ABHt2tlBORMrdKobGlTGeqUOCfqrGZirEUINdPIDKbI

{
    "message": "lo sea",
    "trip_id": 5,
    "user_id": 2
}

###

//GET COMMENTS BY TRIPS

GET http://localhost:3000/api/trips/comment/2


### 

POST http://localhost:3000/api/trips/request/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxOCwiZXhwX2F0IjoxNjcyOTA2NjY5LCJpYXQiOjE2NzExNzg2Njl9.-TCWNVtCoDaVCw8UASP3xW-QtQT5qscKeck8ldvJPxA

{
    "users_id" :20,
    "trips_id": 27,
    "user_status":"pending "
}


