
/////////PETICIONES BÁSICAS/////////

GET http://localhost:3000/api/trips

###
POST http://localhost:3000/api/trips
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxOCwiZXhwX2F0IjoxNjczMTc5NDc4LCJpYXQiOjE2NzE0NTE0Nzh9.n717ik80jgGFYKlHXz-F2Dp-2Rrrkq5mi7d61ouj9Jw

{
"destination": "Madrid",
"min_traveler": 3,
"max_traveler": 5,
"min_age": 25,
"max_age":53,
"departure_date": "2022-11-11",
"duration": 6,
"price": 544,
"description": "Madrid",
"status": "finalizado",
"flights": true, "hotel": true, "meals": false, "excursions": true, "rent_car": false, "insurance": false,
"lat": 40,
"lng": -3
}

###
PUT http://localhost:3000/api/trips/edit/40
Content-Type: application/json

{
"min_traveler": 4,
"max_traveler": 6,
"min_age": 25,
"max_age":53,
"departure_date": "2022-11-11",
"duration": 6,
"price": 544,
"description": "testedit",
"flights": true,
"hotel": true,
"meals": true,
"excursion": true,
"rent_car": true,
"insurance": false

}

###

//DELETE BY ID
PUT http://localhost:3000/api/trips/delete/37
###


/////////PETICIONES AVANZADAS/////////

//GET TRIP BY ID
GET http://localhost:3000/api/trips/25
###

//GET TRIPS BY DESTINATION
GET http://localhost:3000/api/trips/destination/creta
###

//GET ALL DESTINATIONS
GET http://localhost:3000/api/trips/destination
###

//GET TRIPS BY USER
GET http://localhost:3000/api/trips/user/6
###

//GET TRIPS CREATED BY USER LOGGED
GET http://localhost:3000/api/trips/user/created
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxOCwiZXhwX2F0IjoxNjczMTc5NDc4LCJpYXQiOjE2NzE0NTE0Nzh9.n717ik80jgGFYKlHXz-F2Dp-2Rrrkq5mi7d61ouj9Jw
###

//GET TRIPS SUSCRIBED BY USER LOGGED
GET http://localhost:3000/api/trips/user/suscribed
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxOCwiZXhwX2F0IjoxNjcyODMyNzI3LCJpYXQiOjE2NzExMDQ3Mjd9.x8Y27M0nsFthq4aqz3P2AhSIaL-GInTSTIYYQ0kABk0
###

//POST COMMENT
POST http://localhost:3000/api/trips/comment/new
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMiwiZXhwX2F0IjoxNjcyNjU4ODE1LCJpYXQiOjE2NzA5MzA4MTV9.ABHt2tlBORMrdKobGlTGeqUOCfqrGZirEUINdPIDKbI

{
    "message": "lo sea",
    "trip_id": 5,
    "user_id": 2
}

###

//GET COMMENTS BY TRIP
GET http://localhost:3000/api/trips/comment/27
###

//GET ITINERARY BY TRIP
GET http://localhost:3000/api/trips/itinerary/29
###

//GET SUBSCRIBED BY TRIP
GET http://localhost:3000/api/trips/subscribed/41
###

//POST ITINERARY ON TRIPS
POST http://localhost:3000/api/trips/itinerary/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxOCwiZXhwX2F0IjoxNjcyOTE5MDg1LCJpYXQiOjE2NzExOTEwODV9.fbVs_mjOSVzYMF64sEr_WHdlffAowKDA8Up_L2tpLAc

{
    "it_description": "Paseo por Hyde Park",
    "it_date_begin": "2022-12-17",
    "it_date_end": "2022-12-19",
    "trip_id": 29
}

###

###
POST http://localhost:3000/api/trips/request/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxOCwiZXhwX2F0IjoxNjczMDkyNTU4LCJpYXQiOjE2NzEzNjQ1NTh9.DDvKMYCA3f0hwxawiCT8GZuVBsYJMgxWMKeNxHcWvFM

{
    "users_id": 18,
    "trips_id": 25,
    "user_status": "pending"
}
###

//MANAGE USER REQUEST
PUT http://localhost:3000/api/trips/29/18
Content-Type: application/json

{
    "user_status": "aceptada"
}

###

###
// GET GEOMETRY
GET http://localhost:3000/api/trips/geometry/33

###

GET http://localhost:3000/api/trips/suscribed/accepted/24


